swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains propose additional API endpoints for transactions user for ArgentBank Application.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: Api for get transactionId
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: user id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User account retrieved successully
          schema:
            $ref: "#/definitions/idResponse"
        "400":
          description: Invalid Fields
        "404":
          description: page not found
        "500":
          description: Internal Server Error
          
  /user/{id}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
      - User Module Transaction
      summary: API for viewing  transaction
      description: API for viewing  transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          description: transaction id
          type: string
          required: true
        - in: path
          name: id
          description: user id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/userIdTransactionResponse'
        '400':
          description: Invalid Fields
        '404':
          description: page not found
        '500':
          description: Internal Server Error
    post:
        security:
        - Bearer: []
        tags:
        - User Module Transaction
        summary: User Transaction API
        description: User transaction API
        parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          description: transaction id
          type: string
          required: true
        - in: path
          name: id
          description: user id
          required: true
          type: string
        produces:
        - application/json
        responses:
          '200':
            description: Transaction load successfully
            schema:
              $ref: '#/definitions/transactionResponse'
          '400':
            description: Invalid Fields
          '404':
            description: page not found
          '500':
            description: Internal Server Error
    put:
        security:
        - Bearer: []
        tags:
        - User Module Transaction
        summary:  Updating transaction
        description: Updating transaction
        parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionId
          description: transaction id
          type: string
          required: true
        - in: path
          name: id
          description: user id
          required: true
          type: string
        produces:
        - application/json
        responses:
          '200':
            description: Transaction edited Successfully
            schema:
              $ref: '#/definitions/updateTransactionResponse'
          '400':
            description: Invalid Fields
          '404':
            description: page not found
          '500':
            description: Internal Server Error
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: id
    in: header
definitions:
  idResponse :
    properties:
      firstName:
        type: string
      lastName:
        type: string
      transactionIds: 
        items: {}
      userId:
        type: string
  userIdTransactionResponse:
    properties:
      userId:
        type: string
        description: user ID
      transactionId:
        type: string
        description: transaction ID
      amountBalance:
        type: number
  transactionResponse:
    properties:
      userId:
        type: string
        description: user ID
      transactionId:
        type: string
        description: transaction ID
      date:
        type: string
        description: date transaction
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance: 
        type: number
        description: balance after transaction
      type:
        type: string
        description: type of transaction
      category:
        type: string
        description: category  of transaction
      notes:
        type: string
        description: notes about transaction
  updateTransactionResponse:
    properties:
      category:
        type: string
        description: category  of transaction
      notes:
        type: string
        description: notes about transaction
     
 
     
       